name: Build, Test and Analyze Pull Requests

on:
  pull_request:
    types: [opened, synchronize, assigned, reopened]
    branches:
      - master
  push:
    branches:
      - master
  release:
    types: [ published, prereleased ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build/Test
    services:
      #Label used to access the service container
      mysql:
        # Docker Hub image
        image: mysql:8.0.30-oracle
        ports:
          - "3306:3306"
        env:
          MYSQL_DATABASE: digital_learning
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_HOST: localhost
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Build and test with maven
        run: mvn -B clean package --file pom.xml -Dspring.profiles.active=local
        env:
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
          DB_HOST: localhost
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        with:
          report_paths: '**/target/surefire-reports/TEST-*.xml'
        if: ${{ !cancelled() }}